### ISSUE TITLE
README is incorrect and misleading

### ISSUE THREAD

**Issue by evilstickman** [solisoft/paypal_nvp#13]
Thanks for this great gem - it really helps with the pointless glue code needed to talk to paypal. However, there are several issues I thought you should be aware of, particularly in the README file:

1 - You mention that the recommended way to install the gem is to install it using `sudo gem install paypal_nvp`. By using it with sudo, you're installing this into the root gemset instead of the local gemset for the current user. This makes the gem available too widely, and can also cause permissions issues due to being granted root access. Unless there's a very good reason (and I can't see any based on reviewing the code), you will at least want to remove `sudo` from that line, and it'd probably be wise to recommend something like bundler for gem management

2 - Your section on specifying the version in the `data` hash is inaccurate. Based on your code the version defaults to 50 in the `@extras` member variable. You then call `data.merge!(@extras)` when performing the call, and the problem here is that this call will overwrite any versions specified in the data hash - see [http://apidock.com/ruby/Hash/merge!](http://apidock.com/ruby/Hash/merge!) for more info. Thus, specifying a version in the call to `call_paypal` will never work (and this is confirmed by my local testing)

Again, great work on the gem, but it seems like some elements need a bit of polish and updating

**Comment by solisoft** [comment]
Hi @evilstickman, this gem is a very old one actually, and yes you're right it need some refactoring :)
It was done before bundler age, so yes I'll have to update the documentation.
Please feel free to fork, update and submit a pull request. I'll check it and deploy it !

Thank for your sights

**Comment by evilstickman** [comment]
Thanks for the response, @solisoft  - I'll fork it and do some cleanup, then issue a PR back to the source gem

**Comment by evilstickman** [comment]
https://github.com/solisoft/paypal_nvp/pull/14

**Comment by solisoft** [comment]
Fixed, merged and deployed
